spring.application.name=learn-user
server.port=9201

spring.datasource.jdbc-url=jdbc:mysql://192.119.106.219:3306/learn?useSSL=false
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=pig
spring.datasource.password=123456

# jwt 配置
# header:凭证(校验的变量名)
custom.jwt.header=Authorization
# 有效期1天(单位:s)
custom.jwt.expire=5184000
# secret: 秘钥(普通字符串) 不能太短，太短可能会导致报错
custom.jwt.secret=MC4CAQACBQDMRtFtAgMBAAECBQCWhcIt
# 签发者
custom.jwt.issuer=Sage

#management.endpoints.web.exposure.include=loggers
#management.endpoint.loggers.enabled=true

#logging.level.root=DEBUG
#logging.level.com.prosper=DEBUG
