spring.application.name=learn-service
server.port=9202

#eureka
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

#datasource
spring.datasource.jdbc-url=jdbc:mysql://110.40.183.130:3306/learn?useSSL=false&characterEncoding=utf-8&tcpKeepAlive=true&autoReconnect=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=11110000

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=500
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.keepalive-time=15000

#mybatis
mybatis.configuration.map-underscore-to-camel-case=true

#log
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#mail
spring.mail.host=smtp.126.com
spring.mail.port=25
spring.mail.username=deaconcc@126.com
spring.mail.password=SQvpYXGC6kaYKNqw
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true; 

# redis
spring.data.redis.host=110.40.183.130
spring.date.redis.port=6379

# sa-token
sa-token.timeout=72000
sa-token.token-name=token
sa-token.storage-typee=cookie
sa-token.cookie-http-only: true
sa-token.cookie-secure: true

logging.level.org.apache.ibatis=DEBUG
logging.level.java.sql=DEBUG
logging.level.org.mybatis.spring.SqlSessionFactoryBean=DEBUG

#management
#management.endpoints.web.exposure.include=loggers
#management.endpoint.loggers.enabled=true

#logging
#logging.level.root=DEBUG
#logging.level.com.prosper=DEBUG

