#eureka
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.fetch-registry=true
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring.application.name=learn-front
server.port=80

posting.count = 2;

spring.thymeleaf.cache=false
# https://cloud.baidu.com/article/3316970
spring.thymeleaf.mode=LEGACYHTML5

# redis
spring.data.redis.host=localhost
spring.date.redis.port=6379

# sa-token
sa-token.timeout=3600 
sa-token.token-name=token
sa-token.storage-typee=cookie
sa-token.cookie-http-only: true
sa-token.cookie-secure: true

