/**
 * 后端错误码常量
 * 与后端 ErrorCode.java 保持一致
 */

// 通用业务相关 10xx
export const NOT_SUPPORTED = 1001
export const INVALID_PARAMETER = 1002
export const JSON_PROCESSING_ERROR = 1003
export const INVALID_DATE = 1004
export const INVALID_DAYS_RANGE = 1005
export const PERMISSION_DENIED = 1006
export const NOT_FOUND = 1007

// 用户认证相关 11xx
export const USER_NOT_LOGIN = 1001
export const USER_NOT_FOUND = 1101
export const USER_ALREADY_EXISTS = 1102
export const USER_PASSWORD_WRONG = 1103
export const USER_EMAIL_NOT_VALIDATED = 1104
export const USER_INVALID_EMAIL_FORMAT = 1105
export const USER_INVALID_USERNAME_LENGTH = 1106
export const USER_INVALID_PASSWORD_LENGTH = 1107
export const USER_VERIFICATION_CODE_INVALID = 1108
export const USER_VERIFICATION_CODE_NOT_FOUND = 1109
export const USER_ALREADY_FOLLOWED = 1110
export const USER_SUBSCRIPTION_PARSE_ERROR = 1111
export const USER_COURSE_ALREADY_SUBSCRIBED = 1112
export const USER_COURSE_NOT_SUBSCRIBED = 1113
export const USER_BANNED = 1114

// 课程相关 12xx
export const COURSE_NOT_FOUND = 1201
export const COURSE_ALREADY_APPROVED = 1202
export const COURSE_ALREADY_REJECTED = 1203
export const COURSE_STATE_CONFLICT = 1204
export const COURSE_PARENT_NOT_FOUND = 1205
export const COURSE_DELETE_FAILED = 1206
export const COURSE_OPERATION_FAILED = 1207
export const COURSE_BLOCKED = 1208

// 路线图相关 15xx
export const ROADMAP_NOT_FOUND = 1501
export const ROADMAP_CONTENT_INVALID = 1502
export const ROADMAP_PIN_LIMIT_EXCEEDED = 1503

// 学习进度相关 16xx
export const USER_ROADMAP_NOT_FOUND = 1601
export const USER_COURSE_NOT_FOUND = 1602
export const USER_COURSE_PROGRESS_INVALID = 1603
export const LEARNING_PROGRESS_SYNC_FAILED = 1604
export const LEARNING_PROGRESS_REDIS_FAILED = 1605
export const LEARNING_PROGRESS_DATABASE_FAILED = 1606
export const LEARNING_PROGRESS_INVALID_NODE_ID = 1607
export const LEARNING_PROGRESS_TOC_PARSE_FAILED = 1608

// 数据解析相关 17xx
export const JSON_PARSE_ERROR = 1701
export const CONTENT_HASH_ERROR = 1702

// 评论相关 14xx
export const COMMENT_NOT_FOUND = 1401
export const COMMENT_PARENT_NOT_FOUND = 1402
export const COMMENT_INVALID_TYPE = 1403
export const COMMENT_OBJECT_NOT_FOUND = 1404

// 内容管理相关 13xx
export const CONTENTS_COURSE_NOT_FOUND = 1301
export const CONTENTS_POST_NOT_FOUND = 1302
export const CONTENTS_PINNED_ITEMS_LIMIT_EXCEEDED = 1303
export const CONTENTS_INVALID_POST_TYPE = 1304
export const POSTING_INVALID_PARAMETER = 1305
export const POSTING_CONTENT_PARSE_FAILED = 1306
export const POSTING_NODE_NOT_FOUND = 1307
export const POSTING_LIST_QUERY_FAILED = 1308
export const NODE_BLOCKED = 1309

// 目录管理相关 18xx
export const TOC_USER_TOC_NOT_FOUND = 1801
export const TOC_INDEX_OUT_OF_BOUNDS = 1802

// 课程排行相关 19xx
export const COURSE_RANKING_INVALID_LIMIT = 1901
export const COURSE_RANKING_REDIS_OPERATION_FAILED = 1902

// 消息相关 20xx
export const MESSAGE_NOT_FOUND = 2001

// 专业相关 21xx
export const PROFESSION_NOT_FOUND = 2101
export const PROFESSION_NAME_REQUIRED = 2102
export const PROFESSION_ALREADY_APPROVED = 2103
export const PROFESSION_ALREADY_REJECTED = 2104
export const PROFESSION_STATE_CONFLICT = 2105
export const PROFESSION_HOT_LIST_FAILED = 2106
export const PROFESSION_INVALID_LIMIT = 2107
export const PROFESSION_BLOCKED = 2108

// 记忆卡片相关 22xx
export const MEMORY_CARD_DECK_NOT_FOUND = 2201
export const MEMORY_CARD_NOT_FOUND = 2202
export const MEMORY_CARD_VERSION_NOT_FOUND = 2203
export const MEMORY_BANK_COURSE_NOT_FOUND = 2204
export const SRS_STATE_NOT_FOUND = 2205
export const MEMORY_CARD_DECK_ALREADY_EXISTS = 2206
export const INVALID_REVIEW_RESULT = 2207
export const INVALID_FREQUENCY_SETTING = 2208
export const INVALID_COURSE_STUDY_STATUS = 2209

// 系统错误 9xxx
export const SYSTEM_ERROR = 9999
export const DATABASE_ERROR = 9001
export const EXTERNAL_SERVICE_ERROR = 9002
export const REDIS_CONNECTION_ERROR = 9003
export const REDIS_OPERATION_ERROR = 9004
export const AI_SERVICE_REQUEST_FAILED = 9005
export const AI_SERVICE_RESPONSE_PARSE_FAILED = 9006
export const AI_SERVICE_INVALID_PARAMETER = 9007
export const SCHEDULER_TASK_FAILED = 9008
export const SCHEDULER_DATA_SYNC_FAILED = 9009

// 导出所有错误码对象
export const ErrorCodes = {
  NOT_SUPPORTED,
  INVALID_PARAMETER,
  JSON_PROCESSING_ERROR,
  INVALID_DATE,
  INVALID_DAYS_RANGE,
  PERMISSION_DENIED,
  NOT_FOUND,
  USER_NOT_LOGIN,
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  USER_PASSWORD_WRONG,
  USER_EMAIL_NOT_VALIDATED,
  USER_INVALID_EMAIL_FORMAT,
  USER_INVALID_USERNAME_LENGTH,
  USER_INVALID_PASSWORD_LENGTH,
  USER_VERIFICATION_CODE_INVALID,
  USER_VERIFICATION_CODE_NOT_FOUND,
  USER_ALREADY_FOLLOWED,
  USER_SUBSCRIPTION_PARSE_ERROR,
  USER_COURSE_ALREADY_SUBSCRIBED,
  USER_COURSE_NOT_SUBSCRIBED,
  USER_BANNED,
  COURSE_NOT_FOUND,
  COURSE_ALREADY_APPROVED,
  COURSE_ALREADY_REJECTED,
  COURSE_STATE_CONFLICT,
  COURSE_PARENT_NOT_FOUND,
  COURSE_DELETE_FAILED,
  COURSE_OPERATION_FAILED,
  COURSE_BLOCKED,
  ROADMAP_NOT_FOUND,
  ROADMAP_CONTENT_INVALID,
  ROADMAP_PIN_LIMIT_EXCEEDED,
  USER_ROADMAP_NOT_FOUND,
  USER_COURSE_NOT_FOUND,
  USER_COURSE_PROGRESS_INVALID,
  LEARNING_PROGRESS_SYNC_FAILED,
  LEARNING_PROGRESS_REDIS_FAILED,
  LEARNING_PROGRESS_DATABASE_FAILED,
  LEARNING_PROGRESS_INVALID_NODE_ID,
  LEARNING_PROGRESS_TOC_PARSE_FAILED,
  JSON_PARSE_ERROR,
  CONTENT_HASH_ERROR,
  COMMENT_NOT_FOUND,
  COMMENT_PARENT_NOT_FOUND,
  COMMENT_INVALID_TYPE,
  COMMENT_OBJECT_NOT_FOUND,
  CONTENTS_COURSE_NOT_FOUND,
  CONTENTS_POST_NOT_FOUND,
  CONTENTS_PINNED_ITEMS_LIMIT_EXCEEDED,
  CONTENTS_INVALID_POST_TYPE,
  POSTING_INVALID_PARAMETER,
  POSTING_CONTENT_PARSE_FAILED,
  POSTING_NODE_NOT_FOUND,
  POSTING_LIST_QUERY_FAILED,
  NODE_BLOCKED,
  TOC_USER_TOC_NOT_FOUND,
  TOC_INDEX_OUT_OF_BOUNDS,
  COURSE_RANKING_INVALID_LIMIT,
  COURSE_RANKING_REDIS_OPERATION_FAILED,
  MESSAGE_NOT_FOUND,
  PROFESSION_NOT_FOUND,
  PROFESSION_NAME_REQUIRED,
  PROFESSION_ALREADY_APPROVED,
  PROFESSION_ALREADY_REJECTED,
  PROFESSION_STATE_CONFLICT,
  PROFESSION_HOT_LIST_FAILED,
  PROFESSION_INVALID_LIMIT,
  PROFESSION_BLOCKED,
  MEMORY_CARD_DECK_NOT_FOUND,
  MEMORY_CARD_NOT_FOUND,
  MEMORY_CARD_VERSION_NOT_FOUND,
  MEMORY_BANK_COURSE_NOT_FOUND,
  SRS_STATE_NOT_FOUND,
  MEMORY_CARD_DECK_ALREADY_EXISTS,
  INVALID_REVIEW_RESULT,
  INVALID_FREQUENCY_SETTING,
  INVALID_COURSE_STUDY_STATUS,
  SYSTEM_ERROR,
  DATABASE_ERROR,
  EXTERNAL_SERVICE_ERROR,
  REDIS_CONNECTION_ERROR,
  REDIS_OPERATION_ERROR,
  AI_SERVICE_REQUEST_FAILED,
  AI_SERVICE_RESPONSE_PARSE_FAILED,
  AI_SERVICE_INVALID_PARAMETER,
  SCHEDULER_TASK_FAILED,
  SCHEDULER_DATA_SYNC_FAILED,
}
